### PR TITLE
prepare for release

### PR DESCRIPTION
**Pull request by int-e**
* restore changes that are in the latest Hackage releases (Hackage requires a `default-language` tag)
* add changelogs

Note that I don't have maintainer access on Hackage, so currently I cannot release these myself.

Also, is there anything more to the release process than uploading the packages to Hackage?

And I still can't look at CircleCI without logging in (and I still don't want to do that, there's simply no justification for giving them write access to my repos)

### CODE REVIEW

**Comment by idontgetoutmuch** [comment]
@int-e that's very irksome of CircelCI - I will look to see if I can change the access permissions. Failing that we can move to a different CI provider as the CI script just runs the nix derivation (a one liner).

**Comment by idontgetoutmuch** [comment]
@int-e I added you as maintainer on hackage for rvar, random-source and random-fu. Did you want try uploading? As far as I know, that's it for hackage. I might take a look at stackage to see what else we need to do.

**Comment by int-e** [comment]
I'll be busy for the next hour or so, I can upload the packages then if you don't beat me to it.

**Comment by idontgetoutmuch** [comment]
There's no rush - I am immensely grateful for your contributions - thank you very much

**Comment by int-e** [comment]
cf. https://hackage.haskell.org/package/random-fu-0.2.7.7 and https://hackage.haskell.org/package/random-source-0.3.0.11

**Pull request merged**
